'use client'

/**
 * /p — Pattern share loader
 *
 * Decodes a pattern from URL search params (generated by encodePatternToUrl),
 * loads it into PatternContext, then redirects to /preview.
 *
 * No login required — the full pattern is encoded in the URL itself.
 */

import { Suspense, useEffect } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import { usePattern } from '@/context/PatternContext'
import { decodePatternFromSearch } from '@/lib/patternUrl'

function PatternLoader() {
  const searchParams = useSearchParams()
  const router       = useRouter()
  const { dispatch } = usePattern()

  useEffect(() => {
    const pattern = decodePatternFromSearch(searchParams.toString())
    if (pattern) {
      dispatch({ type: 'SET_PATTERN_DATA', payload: pattern })
      router.replace('/preview')
    } else {
      // Bad / expired link — go home
      router.replace('/')
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <div style={{
      minHeight: '100vh', display: 'flex',
      flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
      background: '#FAF6EF', gap: 14,
    }}>
      <div style={{ fontSize: 44 }}>🧶</div>
      <p style={{ fontFamily: "'Playfair Display', serif", fontSize: 20, fontWeight: 700, color: '#2C2218' }}>
        Opening your pattern…
      </p>
      <p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 13, color: '#9A8878' }}>
        Just a moment
      </p>
    </div>
  )
}

export default function PatternSharePage() {
  return (
    <Suspense fallback={
      <div style={{
        minHeight: '100vh', display: 'flex',
        flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
        background: '#FAF6EF', gap: 14,
      }}>
        <div style={{ fontSize: 44 }}>🧶</div>
        <p style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 14, color: '#9A8878' }}>
          Loading…
        </p>
      </div>
    }>
      <PatternLoader />
    </Suspense>
  )
}
