'use client'

import { useState, useEffect } from 'react'

const STORAGE_KEY = 'cw_engine_banner_dismissed'

export default function RebrandBanner() {
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    // Only show if not already dismissed
    if (!localStorage.getItem(STORAGE_KEY)) setVisible(true)
  }, [])

  function dismiss() {
    localStorage.setItem(STORAGE_KEY, '1')
    setVisible(false)
  }

  if (!visible) return null

  return (
    <div className="site-banner" style={{ width: '100%', background: '#FEF8F3', borderBottom: '1px solid rgba(196,97,74,0.22)' }}>
      <div style={{
        maxWidth: 700,
        margin: '0 auto',
        padding: '9px 40px 9px 16px',
        display: 'flex',
        alignItems: 'center',
        gap: 10,
        position: 'relative',
      }}>
        <span style={{ fontSize: 14, flexShrink: 0 }}>⚙️</span>
        <p style={{
          fontFamily: "'DM Sans', sans-serif",
          fontSize: 12,
          color: '#5C4033',
          lineHeight: 1.5,
          margin: 0,
        }}>
          <strong style={{ color: '#C4614A' }}>No AI involved.</strong>{' '}
          Patterns are generated by colour quantization and pixel mapping — a mathematical process
          that runs entirely in your browser. Your photos are never uploaded or sent anywhere.
        </p>
        <button
          onClick={dismiss}
          aria-label="Dismiss"
          style={{
            position: 'absolute',
            right: 8,
            top: '50%',
            transform: 'translateY(-50%)',
            background: 'none',
            border: 'none',
            color: '#C8BFB0',
            fontSize: 18,
            cursor: 'pointer',
            lineHeight: 1,
            padding: '4px 6px',
          }}
        >
          ×
        </button>
      </div>
    </div>
  )
}
